/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FindMatch;

import org.junit.*;
import static org.junit.Assert.*;
import FindMatch.controller.GameController;
import FindMatch.view.GameView;

public class AppTest {
    private GameController controller;
    private GameView game;

    @Before
    public void setUp() {
        controller = new GameController();
        game = new GameView(controller);
    }

    @Test 
    public void testLevelButton() {
        game.easyButton.doClick();
        int gridSize = controller.getGridSize();
        assertEquals(gridSize,4);
    }
}
